### ISSUE TITLE
Fullscreen is broken.

### ISSUE THREAD

**Issue by ManuLinares** [caarlos0/timer#110]
When running with the -f flag, display is borked.

![alacritty_Screenshot_2024-07-14_15-33-59](https://github.com/user-attachments/assets/45bcd745-7f51-4e2d-9d93-d7d4a3c017e3)
![xfce4-terminal_Screenshot_2024-07-14_15-34-25](https://github.com/user-attachments/assets/75b48589-3d8e-414c-a57b-6fec00608f90)

Archlinux
timer-bin 1.4.4-1
alacritty 0.13.2-2
xfce4-terminal 1.1.3-1

**Comment by caarlos0** [comment]
hey, thanks for the heads up, fixed

**Comment by ManuLinares** [comment]
> hey, thanks for the heads up, fixed

Thanks to you, would you make a release for this fix?

**Comment by caarlos0** [comment]
doing it rn
