### ISSUE TITLE
Non zero exit code on SIGINT

### ISSUE THREAD

**Issue by antosha417** [caarlos0/timer#40]
Hey! 
When I want to schedule some command to execute later I can do `timer 10s && ./some_command.sh`. 
I think it would be nice to have the ability to cancel the execution. I would expect sending `SIGINT` would do it, but timer exits with zero code and `some_command.sh` then executes immediately. 

What do you think? Does it make sense?

**Comment by caarlos0** [comment]
it does make sense yes, wanna PR it?

**Comment by d1psy-sh** [comment]
I would love to help I am on it. I am a nooby but I'll try my best :)
