### ISSUE TITLE
Feature suggestion: alt-screen with flag/ keymap

### ISSUE THREAD

**Issue by d1psy-sh** [caarlos0/timer#46]
As I worked on the app I had the idea to add a flag for an alt-screen option which centers the timer in the middle of an alt-screen in the terminal at start up. You could even add a keybinding to toggle from alt-screen to normal view.

@caarlos0 if you like the idea I would love to make a PR in the next time.

**Comment by caarlos0** [comment]
I think a flag to start it in altscreen would be cool, yeah

**Comment by d1psy-sh** [comment]
On it ;) :+1:
