### ISSUE TITLE
Configurable Update interval

### ISSUE THREAD

**Issue by NyCodeGHG** [caarlos0/timer#50]
I think it would be pretty cool for shorter durations, to increase the update interval to be more than once per second.

**Comment by NyCodeGHG** [comment]
I played a bit around with the code, but it's not fancy as i thought using shorter update intervals. Also there are some issues with floating point numbers when using a really low update interval.

**Comment by caarlos0** [comment]
maybe we can auto tune it, e.g. if duration <1m, refresh every 100ms, if its >1m, every 1s


wdyt?

**Comment by NyCodeGHG** [comment]
that sounds good
