### ISSUE TITLE
Feature Request: Add a Windows install option

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [caarlos0/timer#53]
## TLDR
Include a windows OS section in the list of installs

### Overview
I think having this utility available on windows would be great for a lot of devs. myself included, I think a lot of devs out there do the meat of their dev work on a linux box, but the home OS on their local machine is windows (whether company mandated or some other reason). 

### Potential Solutions
- Include this executable in varyious package managers (winget, chocolatey, scoop)
- script out installing the executable and adding it to either a user's PATH or as an alias in their Powershell profile.

**Comment by Jonathan-Zollinger** [comment]
I'd love to contribute to this project by resolving this request.

**Comment by caarlos0** [comment]
I should probably set that up at some point, yes

**Comment by Jonathan-Zollinger** [comment]
I've installed it on my windows box, would you accept a pull request if I added powershell script in markdown format to add to the readme? I'm happy to add any tests you'd request (ie powershell pester test) to validate install is done properly

**Comment by caarlos0** [comment]
next release will be on winget
