### ISSUE TITLE
Feature suggestion: Add a message when a named timer is over

### ISSUE THREAD

**Issue by victorhck** [caarlos0/timer#7]
I have tested timer in my openSUSE GNU/Linux distro, and looks great! Thanks for your code!!
Let me suggest a feature (please feel free to throw it to trash bin if you dno't think can be useful), to add a message when a named timer is over. for example

`timer 5s -n test

test timer is over`

Thanks a lot!!

PS: Since I'm not developer, I can't provide code to add this feature... I only have spread the word [in my blog](https://victorhckinthefreeworld.com/2022/02/22/timer-como-alternativa-al-comando-sleep-de-gnu/) (in spanish) about this interesting tool...

**Comment by u0nel** [comment]
You can do desktop notifications with this library: https://github.com/gen2brain/beeep

**Comment by victorhck** [comment]
Hey!

great to see my suggestion in the new release!! :)
